Repository ploigos/ploigos-docs, pull requests merged in 2020-09, with the labels that each got.

#23 refactor the diagram libraries
  .gitignore
  images/Libraries/Process Diagrams
  images/Libraries/Process_Diagrams_Sample.png
  images/Libraries/README.md
  images/Scratchpad-Red_Hat.xml
Labels: documentation, enhancement

#25 napsspo-957 Fill in TODOs
  docs/modules/ref-tssc-workflow-components.adoc
Labels: enhancement

#27 images/TSSC_Workflow_Details.png - clean up workflow for done dev to peer review, there was duplicate 'done dev?' forks
  images/TSSC_Workflow_Details.png
  images/tssc_workflows.drawio
Labels: bug
